-- ═══════════════════════════════════════════════════════════════
-- H Vitamin Drip — Run this entire block in Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

-- 1. Add missing columns
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS images text[] DEFAULT '{}';
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS long_description text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS who_is_it_for text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS disclaimer text;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS original_price numeric;

-- 2. Fix bookings table — safely add any missing columns
DO $$ BEGIN
  BEGIN ALTER TABLE public.bookings ADD COLUMN client_name text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN client_email text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN client_phone text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN address text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN preferred_date date; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN preferred_time text; EXCEPTION WHEN duplicate_column THEN NULL; END;
  BEGIN ALTER TABLE public.bookings ADD COLUMN total_amount numeric; EXCEPTION WHEN duplicate_column THEN NULL; END;
END $$;

-- 3. Temporarily allow public insert for seeding (we'll remove after)
DROP POLICY IF EXISTS "Allow seed insert" ON public.products;
CREATE POLICY "Allow seed insert" ON public.products FOR INSERT WITH CHECK (true);

-- 4. Clear existing products and reseed with full data
DELETE FROM public.booking_items;
DELETE FROM public.products;

INSERT INTO public.products (name,slug,tagline,description,long_description,price,original_price,duration,category,image,images,featured,ingredients,benefits,who_is_it_for,disclaimer) VALUES
('Energy Drip (Myers Cocktail)','energy-drip','Combat fatigue, boost stamina & enhance vitality','The Myers Cocktail/Energy Drip is a powerful combination of essential vitamins, minerals, and amino acids designed to boost energy, improve mental clarity, and enhance overall well-being.','This treatment is designed to combat fatigue, boost stamina, and enhance overall vitality. The infusion combines Vitamin C, B vitamins, magnesium, and other essential nutrients directly into the bloodstream, bypassing the digestive system for maximum absorption and immediate results.',170000,NULL,'45–60 minutes','iv-drip','/images/products/serum-bottles-1.png',ARRAY['/images/products/serum-bottles-1.png','/images/products/amber-dropper-bottles.png','/images/products/eye-serum-bottles.png'],true,ARRAY['Vitamin C','B-Complex Vitamins','Vitamin B12','Magnesium','Calcium','Zinc'],ARRAY['Boosts energy levels','Reduces fatigue','Enhances mental clarity','Supports immune function','Improves hydration','Reduces stress'],'Ideal for those suffering from chronic fatigue, burnout, jet lag, or anyone looking to optimise their energy and performance.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Glutathione Detox','glutathione-detox','Powerful detox, skin brightening & antioxidant protection','The Glutathione IV Drip delivers a potent dose of glutathione, a powerful antioxidant known for its ability to detoxify the body and brighten the skin.','Glutathione IV drips deliver a concentrated dose of this master antioxidant directly into your bloodstream. Glutathione helps neutralise free radicals, detoxify the liver, and promote radiant, even-toned skin.',150000,NULL,'30–45 minutes','iv-drip','/images/products/amber-dropper-bottles.png',ARRAY['/images/products/amber-dropper-bottles.png','/images/products/spray-bottles.png','/images/products/pump-bottles-cream.png'],true,ARRAY['Glutathione','Vitamin C','Alpha Lipoic Acid'],ARRAY['Brightens skin tone','Detoxifies the liver','Neutralises free radicals','Anti-ageing properties','Boosts immune system','Reduces inflammation'],'Perfect for those seeking skin brightening, detoxification, or antioxidant protection.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('High Dose Vitamin C','high-dose-vitamin-c','Protect cells, reduce inflammation & boost immunity','This treatment harnesses the potent antioxidant properties of vitamin C, known for its ability to protect your cells from damage, reduce inflammation, and enhance your overall health.','The High Dose Vitamin C IV Drip provides a potent infusion of vitamin C. Whether you''re looking to fend off seasonal illnesses, recover faster from strenuous activities, or simply maintain peak health, this treatment is tailored to meet your needs.',130000,NULL,'45–60 minutes','iv-drip','/images/products/spray-bottles.png',ARRAY['/images/products/spray-bottles.png','/images/products/serum-bottles-1.png','/images/products/jars-wooden-lid.png'],true,ARRAY['Ascorbic Acid (Vitamin C)','Sodium Bicarbonate','Sterile Water for Injection'],ARRAY['Powerful antioxidant protection','Boosts immune system','Supports collagen production','Reduces inflammation','Speeds up recovery','Fights seasonal illness'],'Ideal for those looking to strengthen their immune system, recover from illness faster, or support overall cellular health.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('NAD+ Therapy','nad-therapy','Reverse cellular ageing & restore peak energy','NAD+ (Nicotinamide Adenine Dinucleotide) is a vital coenzyme found in every cell of your body, playing a crucial role in energy production, cellular repair, and maintaining optimal function.','As we age, NAD+ levels naturally decline, leading to fatigue, cognitive decline, and other health issues. Our NAD+ Therapy replenishes these essential levels, providing a comprehensive solution to combat the adverse effects of aging, stress, and lifestyle factors.',85000,NULL,'2–4 hours','iv-drip','/images/products/eye-serum-bottles.png',ARRAY['/images/products/eye-serum-bottles.png','/images/products/serum-bottles-1.png','/images/products/pump-bottles-lavender.png'],true,ARRAY['NAD+ (Nicotinamide Adenine Dinucleotide)','Sterile Saline Solution'],ARRAY['Slows cellular ageing','Boosts brain function','Enhances energy production','Supports DNA repair','Improves metabolism','Athletic performance support'],'Suited for those experiencing age-related fatigue, cognitive decline, or anyone seeking to optimise cellular health and performance.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Skin & Hair Drip','skin-hair-drip','Rejuvenate skin & promote healthy hair growth','The Skin + Hair IV Drip is designed to rejuvenate your skin and promote healthier hair growth. Packed with essential vitamins, minerals, and antioxidants.','Our Skin & Hair Drip delivers a powerful blend of biotin, vitamins C and E, zinc, and silica directly into the bloodstream for maximum bioavailability. This treatment targets the root causes of dull skin and hair loss, nourishing follicles and skin cells from within.',160000,NULL,'45–60 minutes','iv-drip','/images/products/pump-bottles-cream.png',ARRAY['/images/products/pump-bottles-cream.png','/images/products/pump-bottles-lavender.png','/images/products/amber-dropper-bottles.png'],true,ARRAY['Biotin (Vitamin B7)','Vitamin C','Vitamin E','Zinc','Silica','B-Complex Vitamins'],ARRAY['Promotes hair growth','Strengthens hair follicles','Brightens skin','Reduces hair loss','Improves skin elasticity','Nourishes nails'],'Perfect for those experiencing hair thinning, dull skin, brittle nails, or anyone wanting to enhance their natural beauty from within.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Immunity Booster','immunity-booster','Fortify your body''s natural defences','Immunity booster therapy is designed to enhance your body''s natural defenses, promoting faster recovery and overall health.','The Immunity IV Drip is specially formulated to support and enhance your immune system. Packed with essential vitamins, minerals, and antioxidants, this IV therapy provides comprehensive immune support.',150000,NULL,'45–60 minutes','iv-drip','/images/products/jars-wooden-lid.png',ARRAY['/images/products/jars-wooden-lid.png','/images/products/spray-bottles.png','/images/products/serum-bottles-1.png'],false,ARRAY['High-Dose Vitamin C','Zinc','B-Complex Vitamins','Selenium','Magnesium'],ARRAY['Strengthens immune system','Faster illness recovery','Reduces severity of cold & flu','Anti-inflammatory','Antioxidant protection','Increases energy'],'Ideal during cold & flu season, after illness, before travel, or for anyone wanting to maintain a strong immune system.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Detox Therapy','detox-therapy','Flush toxins, restore balance & refresh your body','This powerful treatment is designed to help you combat the stresses and toxins of modern life, leaving you feeling refreshed and revitalised.','The Detox Drip supports your body''s natural detoxification processes. By infusing a blend of essential vitamins, minerals, and antioxidants directly into the bloodstream, this treatment helps flush out toxins and reduce oxidative stress.',160000,NULL,'45–60 minutes','iv-drip','/images/products/tube-bottles.png',ARRAY['/images/products/tube-bottles.png','/images/products/amber-dropper-bottles.png','/images/products/cream-jars-colored.png'],false,ARRAY['Glutathione','Vitamin C','Alpha Lipoic Acid','B-Complex Vitamins','Magnesium'],ARRAY['Removes toxins','Supports liver health','Reduces oxidative stress','Improves digestion','Boosts energy','Clearer skin'],'Perfect after holidays, festivities, periods of stress, or for anyone seeking a full body reset.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Hydration Drip','hydration-drip','Rehydrate, replenish & revive your body','Our Hydration Drip is the perfect solution to rehydrate your body, replenish vital nutrients, and revive your energy levels.','Whether you''re recovering from intense exercise, a long flight, or a night out, the Hydration Drip rapidly restores optimal fluid balance and electrolytes.',120000,NULL,'30–45 minutes','iv-drip','/images/products/spray-bottles.png',ARRAY['/images/products/spray-bottles.png','/images/products/jars-wooden-lid.png','/images/products/eye-serum-bottles.png'],false,ARRAY['Sterile Saline Solution','Electrolytes','Vitamin C','B-Complex Vitamins','Magnesium'],ARRAY['Rapid rehydration','Electrolyte replenishment','Headache relief','Fatigue recovery','Post-exercise recovery','Hangover relief'],'Perfect for athletes, travellers, those recovering from illness or a hangover, or anyone feeling dehydrated.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Anti-Ageing Therapy','anti-ageing-therapy','Turn back the clock with targeted rejuvenation','A powerful combination of B Vitamins, Glutathione and Amino Acids for anti-ageing and rejuvenating effects.','Our Anti-Ageing IV therapy delivers a potent cocktail of glutathione, B vitamins, amino acids, and antioxidants that work at a cellular level to reverse the signs of ageing, supporting collagen production and promoting cell renewal.',180000,NULL,'45–60 minutes','iv-drip','/images/products/pump-bottles-lavender.png',ARRAY['/images/products/pump-bottles-lavender.png','/images/products/amber-dropper-bottles.png','/images/products/pump-bottles-cream.png'],false,ARRAY['Glutathione','B-Complex Vitamins','Amino Acids','Vitamin C','Coenzyme Q10'],ARRAY['Reduces fine lines','Brightens complexion','Promotes collagen','Cellular regeneration','Antioxidant protection','Improved elasticity'],'Ideal for those wanting to maintain a youthful appearance, reduce signs of ageing, or support long-term skin health.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Fitness Drip','fitness-drip','Recover faster, perform better & stay hydrated','Designed to support recovery, boost energy, and restore hydration. Whether you''re an athlete or a fitness enthusiast, this drip has you covered.','The Fitness Drip is specially formulated for those who push their limits. It delivers amino acids, electrolytes, and performance-enhancing vitamins directly to your muscles for rapid recovery and reduced soreness.',150000,NULL,'45–60 minutes','iv-drip','/images/products/serum-bottles-1.png',ARRAY['/images/products/serum-bottles-1.png','/images/products/tube-bottles.png','/images/products/spray-bottles.png'],false,ARRAY['Amino Acids','Electrolytes','Vitamin C','B-Complex Vitamins','Magnesium','Zinc'],ARRAY['Accelerates recovery','Reduces muscle soreness','Boosts endurance','Improves hydration','Enhances performance','Replenishes nutrients'],'Ideal for athletes, gym-goers, marathon runners, or anyone who engages in regular intense physical activity.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Alpha Lipoic Acid (ALA) Drip','alpha-lipoic-acid','Universal antioxidant for energy & protection','ALA aids in the conversion of nutrients into energy, helping to combat fatigue and enhance physical and mental performance.','Alpha Lipoic Acid is a universal antioxidant that works in both fat and water-soluble environments, making it uniquely effective at combating oxidative stress throughout the body.',140000,NULL,'45–60 minutes','iv-drip','/images/products/amber-dropper-bottles.png',ARRAY['/images/products/amber-dropper-bottles.png','/images/products/eye-serum-bottles.png','/images/products/serum-bottles-1.png'],false,ARRAY['Alpha Lipoic Acid','Vitamin C','B-Complex Vitamins'],ARRAY['Universal antioxidant','Supports nerve health','Blood sugar balance','Boosts energy metabolism','Regenerates other antioxidants','Anti-ageing'],'Recommended for those with diabetes, neuropathy, fatigue, or anyone wanting powerful antioxidant support.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Multi-Vitamin Drip','multivitamin-drip','Comprehensive nutrient infusion for total wellbeing','The MultiVit IV Drip provides a comprehensive blend of essential vitamins and minerals to support your overall health and wellness.','Our Multi-Vitamin Drip is the ultimate wellness maintenance treatment. It delivers a carefully formulated blend of over 20 essential vitamins, minerals, and trace elements directly into your bloodstream for 100% bioavailability.',140000,NULL,'45–60 minutes','iv-drip','/images/products/cream-jars-colored.png',ARRAY['/images/products/cream-jars-colored.png','/images/products/jars-wooden-lid.png','/images/products/pump-bottles-cream.png'],false,ARRAY['Vitamin A','B-Complex Vitamins','Vitamin C','Vitamin D','Vitamin E','Zinc','Magnesium','Selenium'],ARRAY['Complete nutritional support','Boosts energy','Strengthens immunity','Supports metabolism','Improves skin health','Reduces deficiency'],'Ideal for busy professionals, those with poor dietary habits, or anyone wanting comprehensive nutritional support.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Healthy Hair Drip','healthy-hair-drip','Luscious, vibrant hair from the inside out','Struggling with dull, lifeless hair? Healthy Hair IV Therapy is your ultimate solution for achieving luscious, vibrant tresses.','This innovative treatment delivers a potent cocktail of biotin, silica, zinc, and essential amino acids directly to your hair follicles through your bloodstream.',160000,NULL,'45–60 minutes','iv-drip','/images/products/pump-bottles-lavender.png',ARRAY['/images/products/pump-bottles-lavender.png','/images/products/pump-bottles-cream.png','/images/products/amber-dropper-bottles.png'],false,ARRAY['Biotin (Vitamin B7)','Silica','Zinc','Amino Acids','Vitamin C','Iron'],ARRAY['Thicker hair growth','Reduces hair shedding','Strengthens hair shafts','Improves scalp health','Adds shine & lustre','Nourishes follicles'],'For those experiencing hair thinning, excessive shedding, or anyone wanting naturally thicker, healthier hair.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Iron Drip','iron-drip','Overcome iron deficiency & restore your vitality','Iron drip therapy is an innovative solution designed to address iron deficiency and anaemia.','Our Iron Drip delivers iron sucrose directly into the bloodstream, bypassing the digestive system for rapid and effective replenishment of iron stores. Results are often felt within 24-48 hours.',180000,NULL,'1–2 hours','iv-drip','/images/products/tube-bottles.png',ARRAY['/images/products/tube-bottles.png','/images/products/spray-bottles.png','/images/products/serum-bottles-1.png'],false,ARRAY['Iron Sucrose','Sterile Saline Solution'],ARRAY['Corrects iron deficiency','Reduces fatigue','Improves energy levels','Enhances cognitive function','Supports red blood cell production','Improves exercise tolerance'],'Recommended for those with diagnosed iron deficiency anaemia, heavy periods, post-surgery patients, or vegetarians/vegans.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Vitamin B12 Booster','vitamin-b12-booster','Essential energy vitamin for body & mind','The Vitamin B12 Injection (Hydroxocobalamin) is an effective solution for replenishing B12 levels in individuals with a deficiency.','Vitamin B12 plays a critical role in energy production, red blood cell formation, and neurological function. Our Hydroxocobalamin injection is the most bioavailable form of B12.',35000,NULL,'5–10 minutes','booster','/images/products/eye-serum-bottles.png',ARRAY['/images/products/eye-serum-bottles.png','/images/products/amber-dropper-bottles.png','/images/products/serum-bottles-1.png'],true,ARRAY['Hydroxocobalamin (Vitamin B12)'],ARRAY['Boosts energy levels','Improves mood','Supports nerve health','Enhances memory','Promotes red blood cell production','Reduces brain fog'],'Ideal for vegans, vegetarians, those with absorption issues, or anyone experiencing B12 deficiency.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Biotin / Vitamin B7 Booster','biotin-b7-booster','Support hair, skin & nail health from within','Biotin is renowned for its ability to support healthy hair, skin, and nails. It is involved in the metabolism of fats, carbohydrates, and proteins.','Our Biotin injection delivers a high concentration of Vitamin B7 directly into your bloodstream for maximum absorption. Biotin is essential for keratin production.',35000,NULL,'5–10 minutes','booster','/images/products/pump-bottles-cream.png',ARRAY['/images/products/pump-bottles-cream.png','/images/products/pump-bottles-lavender.png','/images/products/eye-serum-bottles.png'],false,ARRAY['Biotin (Vitamin B7)'],ARRAY['Promotes hair growth','Strengthens nails','Improves skin health','Supports metabolism','Enhances energy','Reduces hair loss'],'Perfect for those experiencing hair thinning, brittle nails, or dull skin, or anyone wanting to enhance their appearance.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Vitamin D3 Booster','vitamin-d3-booster','The sunshine vitamin for bones, mood & immunity','Vitamin D3, often referred to as the sunshine vitamin, plays a crucial role in maintaining your bone health, immune system, and mood.','Vitamin D deficiency is extremely common in Nigeria due to limited sunlight exposure. Our Vitamin D3 injection delivers a high therapeutic dose directly into the muscle for rapid and effective absorption.',50000,NULL,'5–10 minutes','booster','/images/products/amber-dropper-bottles.png',ARRAY['/images/products/amber-dropper-bottles.png','/images/products/spray-bottles.png','/images/products/jars-wooden-lid.png'],false,ARRAY['Cholecalciferol (Vitamin D3)'],ARRAY['Supports bone health','Boosts immune system','Improves mood','Reduces fatigue','Supports cardiovascular health','Regulates calcium absorption'],'Recommended for those with vitamin D deficiency, limited sun exposure, or anyone wanting to support bone and immune health.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Magnesium Injection','magnesium-injection','Essential mineral for over 300 body functions','Magnesium is an essential mineral that supports over 300 biochemical reactions in the body.','The Magnesium Injection is a fast and effective way to increase magnesium levels, helping with muscle relaxation, nerve function, energy production, and overall well-being.',40000,NULL,'5–10 minutes','injection','/images/products/jars-wooden-lid.png',ARRAY['/images/products/jars-wooden-lid.png','/images/products/cream-jars-colored.png','/images/products/tube-bottles.png'],false,ARRAY['Magnesium Sulphate'],ARRAY['Reduces muscle cramps','Improves sleep quality','Reduces anxiety & stress','Supports heart health','Boosts energy','Supports bone health'],'Ideal for those with muscle cramps, sleep issues, high stress, or anyone wanting to support overall bodily function.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('B Cocktail (B Complex + B12)','b-cocktail','Complete B vitamin boost for energy & brain health','The B Cocktail injection combines a potent blend of B vitamins and Vitamin B12 to provide a comprehensive energy and neurological boost.','Our B Cocktail injection delivers the complete range of B vitamins in one powerful shot. B vitamins are essential for energy metabolism, nervous system health, hormone production, and cognitive function.',40000,NULL,'5–10 minutes','injection','/images/products/spray-bottles.png',ARRAY['/images/products/spray-bottles.png','/images/products/serum-bottles-1.png','/images/products/eye-serum-bottles.png'],false,ARRAY['B1 (Thiamine)','B2 (Riboflavin)','B3 (Niacin)','B5 (Pantothenic Acid)','B6 (Pyridoxine)','B12 (Hydroxocobalamin)'],ARRAY['Boosts energy levels','Supports brain function','Improves mood','Enhances metabolism','Reduces fatigue','Supports nervous system'],'Great for those needing an energy boost, experiencing brain fog, or wanting to support their overall metabolic health.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Vitamin D Injection','vitamin-d-injection','Fast, effective vitamin D replenishment','The Vitamin D Injection is an effective solution for individuals who need to boost their vitamin D levels quickly and effectively.','Vitamin D is crucial for bone health, immune system function, and overall well-being. This injection ensures optimal vitamin D levels for those who are deficient or unable to get enough through sunlight or diet.',50000,NULL,'5–10 minutes','injection','/images/products/eye-serum-bottles.png',ARRAY['/images/products/eye-serum-bottles.png','/images/products/amber-dropper-bottles.png','/images/products/pump-bottles-cream.png'],false,ARRAY['Vitamin D3 (Cholecalciferol)'],ARRAY['Improves bone density','Boosts immune function','Lifts mood','Reduces fatigue','Supports muscle function','Heart health'],'Recommended for those with low vitamin D levels, especially during limited outdoor activity.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment.'),
('Hay Fever Injection','hay-fever-injection','Fast, long-lasting hay fever relief','Feeling run down by hay fever symptoms? Our Hay Fever Injection provides fast and effective relief from seasonal allergies.','Our Hay Fever Injection delivers anti-inflammatory medication and vitamin C directly into the bloodstream for rapid relief from allergic rhinitis symptoms. This treatment can provide relief for the entire hay fever season.',80000,NULL,'10–15 minutes','injection','/images/products/pump-bottles-lavender.png',ARRAY['/images/products/pump-bottles-lavender.png','/images/products/spray-bottles.png','/images/products/jars-wooden-lid.png'],false,ARRAY['Kenalog (Triamcinolone)','Vitamin C'],ARRAY['Rapid allergy relief','Long-lasting effect','Reduces inflammation','Relieves sneezing & congestion','Supports immune system','Single treatment option'],'Ideal for hay fever sufferers who want fast, sustained relief without taking daily medication.','Individual results may vary. Always consult with a healthcare professional before starting any new treatment. Not suitable for everyone.');

-- 5. Drop the temporary seed policy (RLS back to authenticated-only)
DROP POLICY IF EXISTS "Allow seed insert" ON public.products;

SELECT COUNT(*) AS total_products FROM public.products;
